stages:
  - deploy

deploy-frontend:
  stage: deploy
  tags:
    - vultr_group
  only:
    refs:
      - main
  script:
    - rsync -a --delete --exclude='.git' --exclude='.env' . /home/gitlab-runner/homyak/
    - cd /home/gitlab-runner/homyak
    # --remove-orphans подчищает контейнер backend, оставшийся на сервере от прежних деплоев
    - docker compose up -d --build --remove-orphans frontend
